### ISSUE TITLE
nextcloud cron task

### ISSUE THREAD

**Issue by BigMichi1** [mailcow/mailcow-dockerized-docs#367]
as Nextcloud needs to perform some cron related actions the documentation https://mailcow.github.io/mailcow-dockerized-docs/third_party/third_party-nextcloud/ should be extended to include a part on how to configure/enable the cron task.

see https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html

I achieved it by adding this part to my `docker-compose.override.yml` and running `docker-compose up -d && docker-compose restart ofelia`

```yaml
version: '2.1'
services:
  php-fpm-mailcow:
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.nextcloud-cron.schedule: "@every 5m"
      ofelia.job-exec.nextcloud-cron.command: "su www-data -s /bin/bash -c \"/usr/local/bin/php -f /web/nextcloud/cron.php\""
```
